apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  namespace: edu-reverent-mestorf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx
        name: nginx-l2-devman
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
