apiVersion: v1
kind: Service
metadata:
  name: deployment-nginx
  namespace: edu-reverent-mestorf
spec:
  selector:
    app: nginx-deployment
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30291
  type: NodePort
