apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: edu-reverent-mestorf
spec:
  containers:
    - name: container
      image: nginx
      volumeMounts:
        - mountPath: "/.postgresql"
          name: pg-root-cert
          readOnly: true
  volumes:
    - name: pg-root-cert
      secret:
        secretName: pg-root-cert-edu-reverent-mestorf
        defaultMode: 384
